package fr.tristanmarie.worktreediff.core

import com.google.gson.JsonParser
import java.nio.file.Path
import java.nio.file.Paths
import kotlin.io.path.name

/** One entry of `.aria/learnings.md`, written by `aria:learn`. */
data class AriaLearning(
    /** YYYY-MM-DD when the heading carries one. */
    val date: String?,
    val title: String,
    var context: String? = null,
    var learning: String? = null,
    var tags: List<String> = emptyList(),
    /** 0-based line of the heading, so the view can jump to it. */
    val line: Int,
)

/** `.aria/` as `aria:setup` and `aria:learn` leave it, for one project root. */
data class AriaProjectState(
    val root: String,
    val name: String,
    val projectFile: String? = null,
    /** "Generated by aria:setup on YYYY-MM-DD", when project.md says so. */
    val generated: String? = null,
    /** First prose paragraph of project.md: the overview, not the whole file. */
    val summary: String? = null,
    val learningsFile: String? = null,
    val learnings: List<AriaLearning> = emptyList(),
)

data class AriaMemoryEntry(val file: String, val filePath: String, val description: String)

data class AriaExternal(val location: String, val description: String)

data class AriaMemory(
    val dir: String,
    val exists: Boolean,
    val indexPath: String? = null,
    val updated: String? = null,
    val entries: List<AriaMemoryEntry> = emptyList(),
    /** Rows of the External References table: paths elsewhere on the machine. */
    val externals: List<AriaExternal> = emptyList(),
    /** Files present on disk but absent from the index. */
    val unlisted: List<String> = emptyList(),
    /** Index rows whose file is not on disk. */
    val missing: List<String> = emptyList(),
)

data class AriaInfo(
    val plugin: AriaPlugin,
    val pluginDescription: String?,
    val projects: List<AriaProjectState>,
    val memory: AriaMemory,
)

private val LEARNING_HEADING = Regex("""^###\s+(?:(\d{4}-\d{2}-\d{2})\s*[—–-]\s*)?(.+?)\s*$""")
private val FIELD = Regex("""^\*\*(Context|Learning|Tags):\*\*\s*(.*)$""")

private fun clean(text: String): String = text
    .replace(Regex("""\*\*(.+?)\*\*"""), "$1")
    .replace(Regex("`(.+?)`"), "$1")
    .replace(Regex("""\[(.+?)]\(.+?\)"""), "$1")
    .trim()

/** Reads the dated entries of a `.aria/learnings.md`, most recent first. */
fun parseLearnings(markdown: String): List<AriaLearning> {
    val learnings = mutableListOf<AriaLearning>()
    var current: AriaLearning? = null
    for ((i, line) in markdown.lines().withIndex()) {
        val heading = LEARNING_HEADING.find(line)
        if (heading != null) {
            val created = AriaLearning(
                date = heading.groupValues[1].ifEmpty { null },
                title = clean(heading.groupValues[2]),
                line = i,
            )
            learnings.add(created)
            current = created
            continue
        }
        val target = current ?: continue
        val field = FIELD.find(line) ?: continue
        val value = clean(field.groupValues[2])
        when (field.groupValues[1]) {
            "Context" -> target.context = value
            "Learning" -> target.learning = value
            else -> target.tags = value.split(',').map { it.trim() }.filter { it.isNotEmpty() }
        }
    }
    // Undated entries keep their file order at the end rather than sorting as empty strings.
    return learnings.sortedByDescending { it.date ?: "" }
}

data class MemoryIndex(val updated: String?, val entries: List<Pair<String, String>>, val externals: List<AriaExternal>)

/**
 * Reads `~/.claude/aria/_index.md`. The file holds two tables with the same shape: `## Files`
 * and `## External References`; the current heading decides which table a row belongs to.
 */
fun parseMemoryIndex(markdown: String): MemoryIndex {
    val updated = Regex("""^Last updated:\s*(\S+)""", RegexOption.MULTILINE).find(markdown)?.groupValues?.get(1)
    val entries = mutableListOf<Pair<String, String>>()
    val externals = mutableListOf<AriaExternal>()
    var inFiles = false
    val headingRe = Regex("""^##\s+(.+?)\s*$""")
    val rowRe = Regex("""^\|\s*`([^`]+)`\s*\|\s*(.+?)\s*\|\s*$""")
    for (line in markdown.lines()) {
        val heading = headingRe.find(line)
        if (heading != null) {
            inFiles = heading.groupValues[1].trim().equals("files", ignoreCase = true)
            continue
        }
        val row = rowRe.find(line) ?: continue
        if (inFiles) entries.add(row.groupValues[1] to clean(row.groupValues[2]))
        else externals.add(AriaExternal(row.groupValues[1], clean(row.groupValues[2])))
    }
    return MemoryIndex(updated, entries, externals)
}

/** Reads `.aria/` for one project root. Returns null when aria:setup never ran there. */
private fun readProjectState(root: String): AriaProjectState? {
    val dir = Paths.get(root, ".aria")
    val projectMd = readIfPresent(dir.resolve("project.md"))
    val learningsMd = readIfPresent(dir.resolve("learnings.md"))
    if (projectMd == null && learningsMd == null) return null

    var state = AriaProjectState(
        root = root,
        name = Paths.get(root).name,
        learnings = learningsMd?.let(::parseLearnings) ?: emptyList(),
    )
    if (projectMd != null) {
        val overview = Regex("""##\s+Overview\s*\n+([^\n]+)""").find(projectMd)
        state = state.copy(
            projectFile = slashes(dir.resolve("project.md")),
            generated = Regex("""aria:setup on ([0-9-]+)""").find(projectMd)?.groupValues?.get(1),
            summary = overview?.let { clean(it.groupValues[1]) },
        )
    }
    if (learningsMd != null) {
        state = state.copy(learningsFile = slashes(dir.resolve("learnings.md")))
    }
    return state
}

/**
 * Gathers everything aria leaves on this machine. `.aria/` in a repository is the plugin's
 * project state, while `~/.claude/aria/` is a personal memory directory that the plugin
 * neither writes nor reads. They are reported separately for that reason.
 */
fun collectAriaInfo(home: String, roots: List<String>): AriaInfo {
    val plugin = detectAriaPlugin(home)

    var pluginDescription: String? = null
    if (plugin.installed) {
        val cache = Paths.get(home, ".claude", "plugins", "cache")
        for (marketplace in listDir(cache)) {
            val manifest = readIfPresent(
                marketplace.resolve("aria").resolve(plugin.version ?: "").resolve(".claude-plugin").resolve("plugin.json"),
            ) ?: continue
            pluginDescription = try {
                JsonParser.parseString(manifest).asJsonObject.get("description")?.asString
            } catch (_: Exception) {
                null
            }
            break
        }
    }

    val projects = roots.mapNotNull(::readProjectState)

    val memoryDir: Path = Paths.get(home, ".claude", "aria")
    var memory = AriaMemory(dir = slashes(memoryDir), exists = false)
    val indexMd = readIfPresent(memoryDir.resolve("_index.md"))
    if (indexMd != null) {
        val parsed = parseMemoryIndex(indexMd)
        val entries = parsed.entries.map { (file, description) ->
            AriaMemoryEntry(file, slashes(memoryDir.resolve(file)), description)
        }
        val onDisk = listDir(memoryDir).map { it.name }.filter { it.endsWith(".md") && it != "_index.md" }
        val listed = entries.map { it.file }.toSet()
        val present = onDisk.toSet()
        memory = AriaMemory(
            dir = slashes(memoryDir),
            exists = true,
            indexPath = slashes(memoryDir.resolve("_index.md")),
            updated = parsed.updated,
            entries = entries,
            externals = parsed.externals,
            unlisted = onDisk.filter { it !in listed },
            missing = entries.filter { it.file !in present }.map { it.file },
        )
    }

    return AriaInfo(plugin, pluginDescription, projects, memory)
}
